learning_note/learning_note/urls.py
"""管理项目中的所有url所需的函数&模块"""
from django.conf.urls import url, include
from django.contrib import admin

# 记录项目中所有apps的URL
urlpatterns = [
    # 模块admin.site.urls定义了管理网站的URL
    url(r'^admin/', admin.site.urls),
    # 添加应用程序learning_notes的URL
    url(r'', include('learning_notes.urls', namespace='learning_notes')),
    # 应用程序users的URL模式,匹配以‘users’打头的URL
    url(r'^users/', include('users.urls', namespace='users')),
]

learning_note/learning_notes/urls.py
"""定义应用程序learning_notes的URL模式"""
# Django 的url函数
from django.conf.urls import url
# 本地项目的视图，用于映射本地URL到视图函数
from . import views

# 包含应用程序的URL模式的列表
urlpatterns = [
    # 项目主页的一个URL模式
    # Python忽略项目的基础URL,r'^$'直接匹配到基础URL;当请求的URL不与任何URL模式
    #匹配时，Djang返回一个错误页面.
    # Django会调用视图函数views.index().
    # name实参指定了这个URL模式的名称，以便能够在代码的其他地方引用它(index).
    url(r'^$', views.index, name='index'),
    # 呈现所有主题页面的URL模式
    url(r'^topics/$', views.topics, name='topics'),
    # 单个主题页面的URL模式
    # topic_id是一个实参,用于存储捕获到的主题的id
    url(r'^topics/(?P<topic_id>\d+)/$', views.topic, name='topic'),
    # 用于添加新主题的网页URL
    url(r'^new_topic/$', views.new_topic, name='new_topic'),
    # 用于添加新条目的页面的URL模式
    # topic_id是一个存储与主题id匹配的数字的变量
    url(r'^new_entry/(?P<topic_id>\d+)/$', views.new_entry, name='new_entry'),
    # 用于编辑条目的页面的URL模式
    url(r'^edit_entry/(?P<entry_id>\d+)/$', views.edit_entry,
        name='edit_entry'),
    #url(r'^site_media/(?P<path>.*)', 'django.views.static.serve',)
]

learning_note/users/urls.py
"""为应用程序users定义URL模式"""

from django.conf.urls import url
# 导入默认视图login
from django.contrib.auth.views import login

from . import views

urlpatterns = [
    # 登陆页面 http://localhost/users/下
    url(r'^login/$', login, {'template_name': 'users/login.html'},
        name='login'),
    # 注销URL:将请求发送给函数logout_view()
    url(r'^logout/$', views.logout_view, name='logout'),
    # 注册页面
    url(r'^register/$', views.register, name='register'),
]

learning_note/learning_notes/models.py
#!/usr/bin/env python3
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Topic(models.Model):
    """用户学习笔记的主题"""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    # 关联到User表的外键,将主题关联到提交它的用户
    owner = models.ForeignKey(User)

    def __str__(self):
        """返回数据模型的字符串表示"""
        # Django调用方法__str__()返回属性text来表示关于“主题”的信息
        return self.text

class Entry(models.Model):
    """主题下面的条目内容,按添加时间存储在数据库中"""
    # 数据库外键，引用了表Topic中的一条记录，关联到特定的主题
    topic = models.ForeignKey(Topic)
    # TextField()字段不需要长度限制
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        """数据模型Entry的额外属性的元选项"""
        # 指定条目标题的显示格式
        verbose_name_plural = 'entries'

    def __str__(self):
        """返回模型的字符串表示"""
        # 对字符串进行切片，只显示前50个字符，外加省略号
        if len(self.text) >= 50:
            return self.text[:50] + "..."
        else:
            return self.text

learning_note/learning_notes/forms.py
"""
Django 使用ModelForm类创建表单
    根据models.py中的数据模型自动创建表单
"""
from django import forms

# 导入用于创建表单的数据模型
from .models import Topic, Entry

class TopicForm(forms.ModelForm):
    """与模型Topic相关联的表单"""
    class Meta:
        """管理表单的额外行为的元选项"""
        # 指定要创建表单的数据模型
        model = Topic
        # 表单包含的字段
        fields = ['text']
        # 字段标签为空
        labels = {'text': ''}

class EntryForm(forms.ModelForm):
    """与模型Entry相关联的表单"""
    class Meta:
        """管理表单这个实体本身属性的元选项"""
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        # 小部件widgets是一个HTML表单元素，如单行文本框、多行文本框、下拉列表
        # 设置属性widgets覆盖了Django的默认小部件
        # 类form.Textarea用来指定文本框的宽度(80)等属性
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

learning_note/learning_notes/views.py
r"""
视图函数,处理http请求的数据，类似于CGI,
"""
from django.shortcuts import render
from django.http import HttpResponseRedirect, Http404
from django.core.urlresolvers import reverse
# 函数login_required()将作为装饰器
from django.contrib.auth.decorators import login_required

from .models import Topic, Entry
from .forms import TopicForm, EntryForm

# Create your views here.

def index(request):
    """
    学习笔记的主页视图函数
    参数request是一个http请求对象
    """
    # 函数render()根据视图提供的数据渲染响应
    return render(request, 'learning_notes/index.html')

# 装饰器,先运行login_required()的代码,再运行topics()的代码
# login_required()检查用户是否登陆,仅当用户登录时Django才运行topics()的代码;
# 未登录时就重定向到登陆页面
@login_required
def topics(request):
    """显示所有的主题"""
    # 查询数据库,返回查询集(列表)，按添加时间排序
    # 用户登陆后,request对象将有一个user属性,存储了用户的信息
    # 方法filter()过滤出属主为登录用户的主题
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    # 模板将使用字典数据用于生成网页
    contex = {'topics': topics}
    return render(request, 'learning_notes/topics.html', contex)

@login_required
def topic(request, topic_id):
    """
    显示单个主题及其所有的条目
    接受正则表达式(?P<topic_id>\d+)捕获的id,存在topic_id中
    """
    topic = Topic.objects.get(id=topic_id)
    # 确认请求的主题属于当前用户
    check_topic_owner(request, topic)
    # 降序排列笔记条目
    entries = topic.entry_set.order_by('-date_added')
    # 主题&条目都存储在字典context中
    contex = {'topic': topic, 'entries': entries}
    # 将数据库中的内容context发送给模板topic.html
    return render(request, 'learning_notes/topic.html', contex)

@login_required
def new_topic(request):
    """
    添加新主题
    函数new_topic()将http请求对象作为参数
    保存新主题时,需要设置其属于当前登录用户,owner字段不能为空
    """
    if request.method != 'POST':
        # 未提交数据：创建一个新表单,即一个表单TopicForm类的实例
        form = TopicForm()
    else:
        # POST提交的数据,对数据(request.POST中)进行处理
        form = TopicForm(request.POST)
        # 检查数据的有效性
        if form.is_valid():
            # 先将新主题暂存,不存储到数据库,因为当前没有指定主题的属主
            new_topic = form.save(commit=False)
            # 将新主题的属主设置为当前登录用户
            new_topic.owner = request.user
            # 保存新主题到数据库
            new_topic.save()
            # 保存用户提交的数据后,将浏览器请求重定向到页面topics,查看新增的数据
            # 函数reverse()获取URL模式的URL
            return HttpResponseRedirect(reverse('learning_notes:topics'))
    # 存储表单数据
    context = {'form': form}
    return render(request, 'learning_notes/new_topic.html', context)

@login_required
def new_entry(request, topic_id):
    """
    在特定的主题中添加新条目
    topic_id 用于存储从URL中获得的值
    """
    # 获取topic_id对应的正确主题
    topic = Topic.objects.get(id=topic_id)
    # 核实当前条目的主题关联的用户是否为当前登录用户
    check_topic_owner(request, topic)

    if request.method != 'POST':
        # 未提交数据,创建一个空表单
        form = EntryForm()
    else:
        # POST提交的数据,对数据进行处理
        form = EntryForm(data=request.POST)
        if form.is_valid():
            # 新建一个条目对象(表单数据),将其存储到new_entry;
            # commit=False指定不将其保存到数据库
            new_entry = form.save(commit=False)
            # 设置当前提交的条目的主题(entry与topic分开存储到数据库,通过外键
            #关联)
            new_entry.topic = topic
            # 设置完新条目的主题后将其保存到数据库(注意条目与主题的存储逻辑)
            new_entry.save()
            # 将用户重定向到新增条目所属主题的页面
            # args列表包含重定向URL中的所有实参
            return HttpResponseRedirect(reverse('learning_notes:topic',
                                               args=[topic_id]))

    context = {'topic': topic, 'form': form}
    return render(request, 'learning_notes/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
    """
    编辑既有条目
        - 针对GET请求，返回一个表单，让用户对条目进行编辑;
        - 针对POST请求，将修改后的文本保存到数据库中
    """
    # 根据URL匹配到的条目ID获取用户要修改的条目对象
    entry = Entry.objects.get(id=entry_id)
    # 与要修改的条目关联的主题
    topic = entry.topic
    # 核实当前条目的主题关联的用户是否为当前登录用户
    check_topic_owner(request, topic)

    # 请求方法为GET
    if request.method != 'POST':
        """
        请求方法为GET，使用既有条目对象的内容创建一个表单，显示给用户，并能
        够编辑他们
        """
        form = EntryForm(instance=entry)
    else:
        # POST提交的数据，对数据进行处理
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learning_notes:topic',
                                                args=[topic.id]))

    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'learning_notes/edit_entry.html', context)

def check_topic_owner(request, topic):
    """检查主题关联到的用户是否为当前登录用户"""
    if topic.owner != request.user:
        raise Http404

learning_note/learning_notes/templates/learning_notes/base.html
<!-- 加载django-bootstrap3中的模板标签集 -->
{% load bootstrap3 %}

<!-- 声明此文件的类型为html文档; 使用英语(en) -->
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  
    <!-- title元素,指定浏览器标题栏显示的内容 -->
    <title>墨眉笔记</title>
  
    <!-- django-bootstrap3的自定义模板标签,让Django包含所有的Bootstrap样式文件-->
    {% bootstrap_css %}
    <!-- 此标签启动交互式行为-->
    {% bootstrap_javascript %}

  </head>
  <body>  
    <!-- Static top navnar -->
    <!-- nav元素,表示页面的导航链接部分 -->
    <!-- class指定了选择器(selector),选择器规定了<nav>元素内的内容的样式规则,
     决定了特定样式规则将应用于页面上的哪些元素 -->
    <nav class="navbar navbar-default navbar-static-top">
      <!-- 放置页面内容的容器 -->
      <div class="container">

          <!-- <div class="navbar-header" style="background:#FF5151;color:#FFFFFF"> -->
          <div class="navbar-header">
            <!-- 导航栏转换折叠按钮,在浏览器窗口较小或者移动设备上显示网站时,
             collapsed会使导航栏折叠起来 -->
            <button type="button" class="navbar-toggle collapsed"
                data-toggle="collapse" data-target="#navbar"
                aria-expanded="false" aria-controls="navbar">
            </button>
            <!-- 导航栏最左边显示项目名(相当于导航栏商标),并将其设置为到主页的链接 -->
            <a class="navbar-brand" href="{% url 'learning_notes:index' %}">墨眉笔记</a>
          </div>

          <div id="navbar" class="navbar-collapse collapse">
            <!-- 导航栏:<ul>列表,列表项(<li>)由多个链接组成-->
            <ul class="nav navbar-nav">
              <!-- 列表项:是一个链接 -->
              <li><a href="{% url 'learning_notes:topics' %}">Topics</a></li>
            </ul>
            
            <!-- 选择器navbar-right设置一组链接的样式,使其出现在导航栏右边 -->
            <ul class="nav navbar-nav navbar-right">
              <!-- 用户已经登陆 -->
              {% if user.is_authenticated %}
                <!-- 添加注销链接,让每个页面都包含它 -->
                <li><a>Hello, {{ user.username }}.</a></li>
                <li><a href="{% url 'users:logout' %}">log out</a></li>
              <!-- 用户没有登录 -->
              {% else %}
                <!-- 登陆页面的链接 -->
                <li><a href="{% url 'users:register' %}">register</a></li>
                <li><a href="{% url 'users:login' %}">login in</a></li>
                <li><a href="{% url 'users:login' %}">merlin</a></li> -->
              {% endif %}
            </ul>
          </div><!-- /.nav-collapse -->

      </div>
    </nav>

    <!-- 一个div容器,包含两个元素 -->
    <div class="container">

      <!-- class属性值page-header将一系列样式应用到这个块 -->
      <div class="page-header">
        <!-- header块告诉页面的信息以及可执行的操作 -->
        {% block header %}{% endblock header %}
      </div>
      <div>
        {% block content %}{% endblock content %}
      </div>
      <div class="page-header">
        {% block ender %}{% endblock ender %}
      </div>

    </div><!-- /container -->
  
  </body>
</html>

learning_note/learning_notes/templates/learning_notes/edit_entry.html
<!-- 用于编辑条目的表单页面-->
{% extends "learning_notes/base.html" %}
{% load bootstrap3 %}

{% block header %}
  <h3>修改后请单击保存按钮进行保存</h3>
  <p>返回当前条目:<a href="{% url 'learning_notes:topic' topic.id %}">{{ topic }}</a></p>
{% endblock header %}

{% block content %}

  <form action="{% url 'learning_notes:edit_entry' entry.id %}" method='post' class="form">
    
    <!-- 将bootstrap样式应用到列表元素 -->
    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
      <button name="submit" class="btn btn-primary">保存</button>
    {% endbuttons %}

  </form>

{% endblock content %}

learning_note/learning_notes/templates/learning_notes/index.html
<!-- 父模板base.html链接到index.html -->
{% extends "learning_notes/base.html" %}
{%  load svg %}
<!-- django static template tag -->
{% load static %}

{% block header %}
  <!-- jumbotron元素生成一个大框 -->
  <div class='jumbotron' style="background:#FF5151;color:#FFFFFF">
    <h2>开启云笔记时代!</h2>
  </div>
  <!--
  <div class='jumbotron' style="background:#FFE4EF;color:#FFFFFF">
    <img src="{% static "learning_notes/note.jpg" %}" width="300" height="96.3" alt="My image"/>
  </div> -->

  <div class='jumbotron' style="background:#FF5151;color:#FFFFFF"><!-- 粉色FFE3FF -->
    <h2>Track your learning.</h2>
  </div>
{% endblock header %}

<!-- 子模板只需包含当前网页特有的内容 -->
{% block content %}
  <h3>
    <a href="{% url 'users:register' %}">Register an account</a> to make your
    own learning notes, and list the topics you're learning about.
  </h3>
  <h3>
    Whenever you learn somthing new about a topic, make an entry summarizing
    what you've learned.
  </h3>
  <div class='jumbotron' style="background:#FFE3EF;color:#000000"><!-- 粉色 -->
    <!-- static resource -->
    <img src="{% static "learning_notes/note.jpg" %}" width="300" height="533" alt="My image"/>
    <p><font size="5" face="Microsoft YaHei">^_^.....^_^</font></p>
    <img src="{% static "learning_notes/note.jpg" %}" width="300" height="533" alt="My image"/>
    <h2>
      Keep doing, You will success.
    </h2>
  </div>
{% endblock content %}

{% block ender %}
  <h3>Pythoner: merlinhuang</h3>
{% endblock ender %}
 

learning_note/learning_notes/templates/learning_notes/new_entry.html
<!-- 用于添加新条目的模板-->
{% extends "learning_notes/base.html" %}
{% load bootstrap3 %}

{% block header %}
  <h3>在这里为你的主题添加新的内容:</h3>
  <!-- 当前所添加的条目所属的主题，设置为链接,可返回该主题的主页面-->
  <p>返回当前主题:<a href="{% url 'learning_notes:topic' topic.id %}">{{ topic }}</a></p>
{% endblock header %}

{% block content %}

  <!-- 指定将提交的条目数据传递给那个视图函数进行处理-->
  <!-- topic.id用于关联正确的主题-->
  <form action="{% url 'learning_notes:new_entry' topic.id %}" method='post' class="form">
    {% csrf_token %}
    <!-- 使用Bootstrap样式设置表单元素 -->
    {% bootstrap_form form %}
    
    {% buttons %}
      <button name="submit" class="btn btn-primary">添加新内容</button>
    {% endbuttons %}
  </form>

{% endblock content%}

learning_note/learning_notes/templates/learning_notes/new_topic.html
{% extends "learning_notes/base.html" %}
{% load bootstrap3 %}

{% block header %}
  <h3>新建一个你自己的主题:</h3>
{% endblock header %}

{% block content %}
  
  <!-- 实参action指定了将提交的表单数据发送到视图函数new_topic\
    实参method指定浏览器提交数据的请求方法使用POST-->
  <form action="{% url 'learning_notes:new_topic' %}" method='post' class="form">
    <!-- 防止攻击者利用表单获得对服务器未经授权的访问，即跨站请求伪造-->
    {% csrf_token %}
    <!-- 使用bootstrap3样式设置表单元素 -->
    {% bootstrap_form form %}

    <!-- 使用bootstrap3结构定义提交按钮 -->
    {% buttons %}
      <button name="submit" class="btn btn-primary">添加新主题</button>
    {% endbuttons %}
  </form>

{% endblock content %}

learning_note/learning_notes/templates/learning_notes/topic.html
{% extends 'learning_notes/base.html' %}

{% block header %}
  <h2>{{ topic }}</h2>
{% endblock header %}

{% block content %}
  <p>
    <a href="{% url 'learning_notes:new_entry' topic.id %}">添加新的条目</a>
  </p>
 
  {% for entry in entries %}
  <!-- bootstrap面板,是一个带预定义样式的div -->
  <div class="panel panel-default">
    <!-- 面板标题 -->
    <div class="panel-heading">
      <h3>
        {{ entry.date_added|date:'M d, Y H:i' }}
        <small> <!-- small标签使元素变小 -->
          <a href="{% url 'learning_notes:edit_entry' entry.id %}">编辑</a>
        </small>
      </h3>
    </div>

    <!-- 面板主体 -->
    <div class="panel-body">
      {{ entry.text|linebreaks }}
    </div>
  </div> <!-- panel -->
  {% empty %}
    There are no entries for this topic yet.
  {% endfor %}

{% endblock content %}

learning_note/learning_notes/templates/learning_notes/topics.html
<!-- 继承父模板base.html-->
{% extends "learning_notes/base.html" %}
{% load bootstrap3 %}

{% block header %}
  <h2>你的主题列表,点击查看详细条目</h2>
{% endblock header %}

{% block content %}
  <ul>
    {% for topic in topics %}
      <!-- 将主题页面中的每个主题设置为超链接，连接到相应的主题页面 -->
      <li>
        <!-- 针对单个主题依次进行超链接 -->
        <!-- 首次调用topic.id的入口-->
        <h3>
          <a href="{% url 'learning_notes:topic' topic.id %}">{{ topic }}</a>
        </h3>
      </li>
    {% empty %}
      <li>No topics have been added yet.</li>
    {% endfor %}
  </ul>
  
  <h4><a href="{% url 'learning_notes:new_topic' %}">点击这里添加新的主题:</a></h4>
{% endblock content %}